language: node_js
node_js:
  - lts/*

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

install:
  - npm install
  - npm run build

script:
  - echo "Skipping tests"

deploy:
  repo: faroit/faroit.github.io
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-dir: docs/.vuepress/dist
  on:
    branch: master